# Generated by Django 2.0.2 on 2018-03-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_auto_20180312_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='picture',
            new_name='profilepicture',
        ),
    ]
